model:
  num_node_features: 12
  imgsz: 1280
  device: cuda # or cpu or auto

thresholds:
  conf_level: 0.1
  max_dist_thresh: 50
  hsv_upper: [179, 255, 255]
  hsv_lower: [0, 38, 120]

tesseract:
  oem: 3
  psm: 6
  langs: [pof_ocr, eng]
  charset: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_
  ocr_upscale: 3.0